
#############################################################
## Collective Variables                                    ##
#############################################################
colvar {
  name dist1
  distance {
    group1 { 
      psfSegID PROA
      atomNameResidueRange { CA 12-37 }
}
    group2 {
      psfSegID PROB
      atomNameResidueRange { CA 12-37 }
}
  }
}

harmonic {
  colvars { dist1}
  forceConstant 20.0
  centers { 9.73}        # initial distance
  targetCenters {8}  # final distance
  targetNumSteps 250000
}



